[2025-04-04T09:00:40.270+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_images scheduled__2023-05-07T00:00:00+00:00 [queued]>
[2025-04-04T09:00:40.366+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_images scheduled__2023-05-07T00:00:00+00:00 [queued]>
[2025-04-04T09:00:40.369+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T09:00:40.370+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-04T09:00:40.372+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T09:00:40.458+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): download_images> on 2023-05-07 00:00:00+00:00
[2025-04-04T09:00:40.468+0000] {standard_task_runner.py:55} INFO - Started process 1038 to run task
[2025-04-04T09:00:40.477+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'download_images', 'scheduled__2023-05-07T00:00:00+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/dagv2_data_collect.py', '--cfg-path', '/tmp/tmp1gsv_7h1']
[2025-04-04T09:00:40.478+0000] {standard_task_runner.py:83} INFO - Job 250: Subtask download_images
[2025-04-04T09:00:40.520+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T09:00:40.648+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T09:00:40.815+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.download_images scheduled__2023-05-07T00:00:00+00:00 [running]> on host 91a2461e5846
[2025-04-04T09:00:41.195+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=download_images
AIRFLOW_CTX_EXECUTION_DATE=2023-05-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-07T00:00:00+00:00
[2025-04-04T09:00:41.519+0000] {python.py:177} INFO - Done. Returned value was: [None, None]
[2025-04-04T09:00:41.722+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=download_and_store_images, task_id=download_images, execution_date=20230507T000000, start_date=20250404T090040, end_date=20250404T090041
[2025-04-04T09:00:42.461+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-04-04T09:00:42.628+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
