[2025-04-04T09:00:51.062+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_images scheduled__2023-05-12T00:00:00+00:00 [queued]>
[2025-04-04T09:00:51.158+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_images scheduled__2023-05-12T00:00:00+00:00 [queued]>
[2025-04-04T09:00:51.170+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T09:00:51.170+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-04T09:00:51.171+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T09:00:51.298+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): download_images> on 2023-05-12 00:00:00+00:00
[2025-04-04T09:00:51.317+0000] {standard_task_runner.py:55} INFO - Started process 1080 to run task
[2025-04-04T09:00:51.337+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'download_images', 'scheduled__2023-05-12T00:00:00+00:00', '--job-id', '265', '--raw', '--subdir', 'DAGS_FOLDER/dagv2_data_collect.py', '--cfg-path', '/tmp/tmpytwth0gf']
[2025-04-04T09:00:51.342+0000] {standard_task_runner.py:83} INFO - Job 265: Subtask download_images
[2025-04-04T09:00:51.400+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T09:00:51.526+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T09:00:51.808+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.download_images scheduled__2023-05-12T00:00:00+00:00 [running]> on host 91a2461e5846
[2025-04-04T09:00:52.588+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=download_images
AIRFLOW_CTX_EXECUTION_DATE=2023-05-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-12T00:00:00+00:00
[2025-04-04T09:00:53.067+0000] {python.py:177} INFO - Done. Returned value was: [None, None]
[2025-04-04T09:00:53.178+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=download_and_store_images, task_id=download_images, execution_date=20230512T000000, start_date=20250404T090051, end_date=20250404T090053
[2025-04-04T09:00:53.251+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-04-04T09:00:53.358+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
