[2025-04-04T10:19:37.626+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2025-04-04T10:19:37.992+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2025-04-04T10:19:37.993+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T10:19:37.995+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-04T10:19:37.996+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T10:19:38.252+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): download_and_upload_images> on 2024-01-30 00:00:00+00:00
[2025-04-04T10:19:38.344+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'download_and_upload_images', 'scheduled__2024-01-30T00:00:00+00:00', '--job-id', '781', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_collect.py', '--cfg-path', '/tmp/tmpdps9yrkr']
[2025-04-04T10:19:38.331+0000] {standard_task_runner.py:55} INFO - Started process 89 to run task
[2025-04-04T10:19:38.356+0000] {standard_task_runner.py:83} INFO - Job 781: Subtask download_and_upload_images
[2025-04-04T10:19:38.817+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T10:19:39.453+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T10:19:40.413+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-01-30T00:00:00+00:00 [running]> on host 0df80d73d4ff
[2025-04-04T10:19:43.396+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=download_and_upload_images
AIRFLOW_CTX_EXECUTION_DATE=2024-01-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-30T00:00:00+00:00
[2025-04-04T10:19:47.376+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:19:47.399+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:19:47.406+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/amazon/aws/utils/connection_wrapper.py:8: DeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
  #

[2025-04-04T10:20:02.699+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:20:02.744+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:20:18.318+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:20:18.335+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:20:30.022+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:20:30.138+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:20:52.454+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:20:52.472+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:07.808+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:07.825+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:18.501+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:18.512+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:27.226+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:27.230+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:34.144+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:34.167+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:40.027+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:40.029+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:44.309+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:44.318+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:49.671+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:49.678+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:54.388+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:54.399+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:02.862+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:02.869+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:07.201+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:07.204+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:11.154+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:11.172+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:19.903+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:19.907+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:25.276+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:25.279+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:30.712+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:30.718+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:36.950+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:36.956+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:42.780+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:42.782+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:50.375+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:50.377+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:54.518+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:54.544+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:58.610+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:58.623+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:05.579+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:05.595+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:11.484+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:11.529+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:15.888+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:15.896+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:20.941+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:20.951+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:28.148+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:28.153+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:34.628+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:34.685+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:39.978+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:40.026+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:45.144+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:45.168+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:55.633+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:55.662+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:24:02.659+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:24:02.663+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:24:06.505+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:24:06.512+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:24:15.479+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:24:15.489+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:24:25.259+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:24:25.268+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:24:37.552+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:24:37.563+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:24:54.526+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:24:54.556+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:26:47.242+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:26:47.267+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:27:05.826+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:27:05.841+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:27:17.095+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:27:17.098+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:27:33.150+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:27:33.155+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:27:44.778+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:27:44.787+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:27:58.038+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:27:58.047+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:28:14.339+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:28:14.353+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:28:27.441+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:28:27.522+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:28:47.666+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:28:47.682+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:30:33.095+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 233, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3057, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3135, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2856, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2974, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-04T10:31:01.840+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:31:01.929+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:31:35.506+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:31:35.838+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:32:08.435+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:32:08.510+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:34:38.695+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:34:38.708+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:34:59.487+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:34:59.495+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:02.426+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:02.432+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:05.770+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:05.778+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:10.315+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:10.345+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:14.714+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:14.715+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:26.863+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:26.875+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:33.151+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:33.155+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:38.161+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:38.165+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:43.561+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:43.564+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:50.495+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:50.655+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:55.957+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:55.967+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:36:03.175+0000] {local_task_job.py:112} ERROR - Received SIGTERM. Terminating subprocesses
[2025-04-04T10:36:03.833+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 89. PIDs of all processes in the group: [89]
[2025-04-04T10:36:03.963+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 89
