[2025-04-04T10:18:59.417+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-01-28T00:00:00+00:00 [queued]>
[2025-04-04T10:18:59.528+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-01-28T00:00:00+00:00 [queued]>
[2025-04-04T10:18:59.543+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T10:18:59.544+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-04T10:18:59.545+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T10:18:59.916+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): download_and_upload_images> on 2024-01-28 00:00:00+00:00
[2025-04-04T10:19:00.162+0000] {standard_task_runner.py:55} INFO - Started process 61 to run task
[2025-04-04T10:19:00.420+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'download_and_upload_images', 'scheduled__2024-01-28T00:00:00+00:00', '--job-id', '778', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_collect.py', '--cfg-path', '/tmp/tmpqk7x7md2']
[2025-04-04T10:19:00.507+0000] {standard_task_runner.py:83} INFO - Job 778: Subtask download_and_upload_images
[2025-04-04T10:19:00.797+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T10:19:01.008+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T10:19:01.256+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-01-28T00:00:00+00:00 [running]> on host 0df80d73d4ff
[2025-04-04T10:19:02.769+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=download_and_upload_images
AIRFLOW_CTX_EXECUTION_DATE=2024-01-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-28T00:00:00+00:00
[2025-04-04T10:19:04.585+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:19:04.630+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:19:04.632+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/amazon/aws/utils/connection_wrapper.py:8: DeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
  #

[2025-04-04T10:19:13.525+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:19:13.530+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:19:20.205+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:19:20.211+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:19:23.848+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:19:23.863+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:19:26.482+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:19:26.487+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:19:33.097+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:19:33.124+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:19:38.462+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:19:38.469+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:19:47.281+0000] {local_task_job.py:273} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-04-04T10:19:47.304+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 61. PIDs of all processes in the group: [61]
[2025-04-04T10:19:47.312+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 61
[2025-04-04T10:19:47.353+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-04T10:19:48.358+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=61, status='terminated', exitcode=0, started='10:18:59') (61) terminated with exit code 0
