[2025-04-04T10:20:00.267+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-02-09T00:00:00+00:00 [queued]>
[2025-04-04T10:20:00.845+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-02-09T00:00:00+00:00 [queued]>
[2025-04-04T10:20:00.885+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T10:20:00.886+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-04T10:20:00.891+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T10:20:01.268+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): download_and_upload_images> on 2024-02-09 00:00:00+00:00
[2025-04-04T10:20:01.307+0000] {standard_task_runner.py:55} INFO - Started process 112 to run task
[2025-04-04T10:20:01.442+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'download_and_upload_images', 'scheduled__2024-02-09T00:00:00+00:00', '--job-id', '789', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_collect.py', '--cfg-path', '/tmp/tmpuwxn13wj']
[2025-04-04T10:20:01.444+0000] {standard_task_runner.py:83} INFO - Job 789: Subtask download_and_upload_images
[2025-04-04T10:20:01.706+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T10:20:02.330+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T10:20:03.089+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-02-09T00:00:00+00:00 [running]> on host 0df80d73d4ff
[2025-04-04T10:20:05.579+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=download_and_upload_images
AIRFLOW_CTX_EXECUTION_DATE=2024-02-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-09T00:00:00+00:00
[2025-04-04T10:20:06.897+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:20:06.982+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:20:06.998+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/amazon/aws/utils/connection_wrapper.py:8: DeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
  #

[2025-04-04T10:20:28.335+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:20:28.387+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:05.891+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:05.932+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:13.360+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:13.401+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:17.954+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:17.957+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:23.662+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:23.681+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:32.385+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:32.401+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:35.603+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:35.605+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:39.091+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:39.098+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:43.787+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:43.789+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:49.254+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:49.259+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:52.281+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:52.293+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:21:58.671+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:21:58.691+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:04.963+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:04.994+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:09.387+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:09.402+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:15.537+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:15.548+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:21.082+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:21.094+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:25.489+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:25.494+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:28.465+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:28.473+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:32.655+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:32.667+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:39.799+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:39.806+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:45.859+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:45.865+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:52.451+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:52.460+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:22:57.432+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:22:57.457+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:03.898+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:03.902+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:13.663+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:13.681+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:19.645+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:19.763+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:27.223+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:27.243+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:35.088+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:35.126+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:41.697+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:41.706+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:46.300+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:46.349+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:52.593+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:52.603+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:23:59.931+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:23:59.934+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:24:10.823+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:24:10.829+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:24:22.542+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:24:22.546+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:24:31.904+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:24:31.923+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:24:44.699+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:24:44.707+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:25:02.466+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:25:02.478+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:26:58.564+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:26:58.580+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:27:10.692+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:27:10.700+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:27:22.723+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:27:22.731+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:27:33.484+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:27:33.487+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:27:45.717+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:27:45.734+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:27:58.534+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:27:58.551+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:28:14.373+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:28:14.446+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:28:27.526+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:28:27.561+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:28:43.110+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:28:43.142+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:30:58.689+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:30:58.695+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:31:26.596+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:31:26.620+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:31:56.433+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:31:56.503+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:33:39.301+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 215, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3057, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3135, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2856, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2974, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-04T10:34:31.246+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:34:33.255+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:34:43.978+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:34:44.125+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:34:53.885+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:34:53.897+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:01.120+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:01.127+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:04.261+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:04.265+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:08.797+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:08.801+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:12.699+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:12.717+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:17.187+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:17.190+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:26.406+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:26.410+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:39.706+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:39.718+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:44.119+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:44.129+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:49.718+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:49.784+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:35:56.112+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T10:35:56.117+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T10:36:02.723+0000] {local_task_job.py:112} ERROR - Received SIGTERM. Terminating subprocesses
[2025-04-04T10:36:03.243+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 112. PIDs of all processes in the group: [112]
[2025-04-04T10:36:03.330+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 112
[2025-04-04T10:36:03.476+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-04T10:36:04.888+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_data_collect.py", line 89, in download_and_upload_images
    upload_to_minio(local_path, new_image_name)
  File "/opt/airflow/dags/dag_data_collect.py", line 40, in upload_to_minio
    bucket_name=bucket_name, replace=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 99, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 70, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 645, in load_file
    client = self.get_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 641, in get_conn
    return self.conn
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 609, in conn
    return self.get_client_type(region_name=self.region_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 578, in get_client_type
    verify=self.verify,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/session.py", line 309, in client
    config=config,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 986, in create_client
    auth_token=auth_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 126, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 229, in _load_service_model
    service_name, 'service-2', api_version=api_version
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 417, in load_service_model
    model = self.load_data(full_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 471, in load_data
    data, _ = self.load_data_with_path(name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 448, in load_data_with_path
    found = self.file_loader.load_file(possible_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 194, in load_file
    data = self._load_file(file_path + ext, open_method)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 181, in _load_file
    return json.loads(payload, object_pairs_hook=OrderedDict)
  File "/usr/local/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1481, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-04-04T10:36:05.058+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=download_and_store_images, task_id=download_and_upload_images, execution_date=20240209T000000, start_date=20250404T102000, end_date=20250404T103604
[2025-04-04T10:36:06.593+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 789 for task download_and_upload_images (Task received SIGTERM signal; 112)
[2025-04-04T10:36:07.925+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=112, status='terminated', exitcode=1, started='10:20:00') (112) terminated with exit code 1
[2025-04-04T10:36:08.447+0000] {local_task_job.py:208} INFO - Task exited with return code 143
[2025-04-04T10:36:10.833+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-04T10:36:10.897+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-04T10:36:11.597+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
