[2025-04-04T09:09:32.668+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2025-04-04T09:09:32.983+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2025-04-04T09:09:33.014+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T09:09:33.063+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-04-04T09:09:33.064+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T09:09:33.614+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): download_and_upload_images> on 2024-01-04 00:00:00+00:00
[2025-04-04T09:09:33.706+0000] {standard_task_runner.py:55} INFO - Started process 74 to run task
[2025-04-04T09:09:33.751+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'download_and_upload_images', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '756', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_collect.py', '--cfg-path', '/tmp/tmpt0_dojmp']
[2025-04-04T09:09:33.754+0000] {standard_task_runner.py:83} INFO - Job 756: Subtask download_and_upload_images
[2025-04-04T09:09:34.123+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T09:09:34.375+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T09:09:34.766+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-01-04T00:00:00+00:00 [running]> on host 91a2461e5846
[2025-04-04T09:09:35.803+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=download_and_upload_images
AIRFLOW_CTX_EXECUTION_DATE=2024-01-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-04T00:00:00+00:00
[2025-04-04T09:09:36.264+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:09:36.270+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:09:36.273+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/amazon/aws/utils/connection_wrapper.py:8: DeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
  #

[2025-04-04T09:09:51.713+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:09:51.729+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:01.332+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:01.337+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:08.850+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:08.862+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:15.386+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:15.397+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:23.257+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:23.265+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:26.294+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:26.299+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:30.111+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:30.113+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:33.604+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:33.607+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:38.489+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:38.498+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:44.097+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:44.104+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:47.800+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:47.804+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:51.190+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:51.196+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:54.716+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:54.719+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:10:57.585+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:10:57.587+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:01.598+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:01.603+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:06.397+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:06.407+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:12.715+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:12.723+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:17.112+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:17.123+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:20.668+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:20.673+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:24.365+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:24.372+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:27.814+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:27.816+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:29.039+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:29.055+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:34.218+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:34.230+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:38.941+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:38.946+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:45.728+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:45.735+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:49.358+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:49.378+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:52.642+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:52.647+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:55.157+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:55.159+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:11:59.281+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:11:59.292+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:12:01.970+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:12:01.975+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:12:04.961+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:12:04.966+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:12:09.629+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:12:09.631+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:12:13.829+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:12:13.832+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:12:18.683+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:12:18.708+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:12:24.152+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:12:24.163+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:12:26.967+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:12:26.980+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:12:34.530+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:12:34.538+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:12:42.908+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:12:42.915+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:12:45.829+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:12:45.838+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:12:52.577+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:12:52.602+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:12:58.511+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:12:58.529+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:13:11.992+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:13:12.005+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:13:15.129+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:13:15.131+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:13:19.102+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:13:19.106+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:13:23.492+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:13:23.494+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:13:29.549+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:13:29.577+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:13:36.166+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:13:36.178+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:13:42.409+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:13:42.420+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:13:46.916+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:13:46.944+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:13:54.220+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:13:54.223+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:14:27.406+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:14:27.417+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:14:37.717+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:14:37.755+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:14:50.791+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:14:50.808+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:15:01.119+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T09:15:01.130+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T09:17:25.777+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/httpsession.py", line 464, in send
    chunked=self._chunked(request.headers),
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/awsrequest.py", line 95, in _send_request
    method, url, body, headers, *args, **kwargs
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/awsrequest.py", line 123, in _send_output
    self.send(msg)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/awsrequest.py", line 218, in send
    return super().send(str)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPConnection object at 0x7faa51c45b10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_data_collect.py", line 80, in download_and_upload_images
    upload_to_minio(local_path, image_name)
  File "/opt/airflow/dags/dag_data_collect.py", line 40, in upload_to_minio
    bucket_name=bucket_name, replace=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 99, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 70, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 646, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
    callback=Callback,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 292, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 758, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 944, in _make_api_call
    operation_model, request_dict, request_context
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 207, in _send_request
    exception,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 361, in _needs_retry
    request_dict=request_dict,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/retryhandler.py", line 285, in __call__
    attempt_number, response, caught_exception
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/retryhandler.py", line 364, in __call__
    attempt_number, response, caught_exception
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/retryhandler.py", line 248, in __call__
    attempt_number, caught_exception
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/httpsession.py", line 484, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://host.docker.internal:9000/images-bucket/00000031.jpg"
[2025-04-04T09:17:35.003+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=download_and_store_images, task_id=download_and_upload_images, execution_date=20240104T000000, start_date=20250404T090932, end_date=20250404T091734
[2025-04-04T09:17:51.252+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 756 for task download_and_upload_images (Could not connect to the endpoint URL: "http://host.docker.internal:9000/images-bucket/00000031.jpg"; 74)
[2025-04-04T09:17:52.289+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-04-04T09:17:53.575+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
