[2025-04-04T15:40:04.788+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-02-17T00:00:00+00:00 [queued]>
[2025-04-04T15:40:05.131+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-02-17T00:00:00+00:00 [queued]>
[2025-04-04T15:40:05.136+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T15:40:05.140+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-04-04T15:40:05.142+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-04-04T15:40:05.742+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): download_and_upload_images> on 2024-02-17 00:00:00+00:00
[2025-04-04T15:40:05.771+0000] {standard_task_runner.py:55} INFO - Started process 718 to run task
[2025-04-04T15:40:05.860+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_and_store_images', 'download_and_upload_images', 'scheduled__2024-02-17T00:00:00+00:00', '--job-id', '821', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_collect.py', '--cfg-path', '/tmp/tmpoq3idmmm']
[2025-04-04T15:40:05.876+0000] {standard_task_runner.py:83} INFO - Job 821: Subtask download_and_upload_images
[2025-04-04T15:40:06.703+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-04-04T15:40:09.149+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-04-04T15:40:11.454+0000] {task_command.py:388} INFO - Running <TaskInstance: download_and_store_images.download_and_upload_images scheduled__2024-02-17T00:00:00+00:00 [running]> on host fd5deae9c635
[2025-04-04T15:41:03.684+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_and_store_images
AIRFLOW_CTX_TASK_ID=download_and_upload_images
AIRFLOW_CTX_EXECUTION_DATE=2024-02-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-17T00:00:00+00:00
[2025-04-04T15:41:47.383+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:41:47.590+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:41:49.755+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/amazon/aws/utils/connection_wrapper.py:8: DeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
  #

[2025-04-04T15:43:28.822+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 215, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3057, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3135, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2856, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2974, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-04T15:43:48.797+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 215, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3057, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3135, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2856, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2974, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-04T15:45:00.012+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 233, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3057, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3135, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2856, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2974, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-04T15:45:17.247+0000] {base_job.py:243} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 215, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3057, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3135, in _merge
    options=options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2856, in get
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2974, in _get_impl
    load_options=load_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 534, in load_on_pk_identity
    bind_arguments=bind_arguments,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-04T15:46:23.404+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:46:23.413+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:46:41.788+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:46:41.790+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:46:44.434+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:46:44.468+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:46:47.895+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:46:47.903+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:46:51.541+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:46:51.585+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:46:55.011+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:46:55.017+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:46:59.146+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:46:59.180+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:01.888+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:01.890+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:05.651+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:05.659+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:08.471+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:08.493+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:10.635+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:10.640+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:14.457+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:14.460+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:18.076+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:18.083+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:21.053+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:21.116+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:26.417+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:26.423+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:31.948+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:31.950+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:34.459+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:34.473+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:36.222+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:36.237+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:38.610+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:38.616+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:41.175+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:41.177+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:43.219+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:43.232+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:45.408+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:45.417+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:48.336+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:48.345+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:51.762+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:51.771+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:54.225+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:54.231+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:56.049+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:56.051+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:47:59.294+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:47:59.296+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:01.973+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:01.980+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:05.299+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:05.303+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:08.017+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:08.025+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:10.975+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:10.989+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:13.175+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:13.189+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:16.058+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:16.066+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:18.241+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:18.249+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:21.114+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:21.121+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:23.771+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:23.779+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:25.867+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:25.871+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:29.644+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:29.652+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:31.620+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:31.627+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:33.197+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:33.199+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:37.161+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:37.163+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:42.097+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:42.099+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:44.652+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:44.658+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:46.570+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:46.579+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:49.851+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:49.857+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:52.411+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:52.414+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:56.677+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:56.683+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:48:59.443+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:48:59.449+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:01.668+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:01.670+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:03.258+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:03.266+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:06.080+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:06.084+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:08.678+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:08.692+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:10.907+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:10.917+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:12.955+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:12.957+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:15.008+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:15.010+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:16.507+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:16.511+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:21.814+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:21.843+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:24.183+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:24.188+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:27.219+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:27.226+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:30.795+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:30.800+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:34.671+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:34.683+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:37.735+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:37.764+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:42.005+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:42.010+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:45.111+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:45.122+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:48.192+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:48.203+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:50.692+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:50.694+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:53.511+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:53.516+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:49:56.465+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:49:56.467+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:50:05.051+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:50:05.097+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:55:37.442+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:55:37.451+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:55:41.906+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:55:41.924+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:55:47.241+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:55:47.277+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:55:53.488+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:55:53.511+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:56:06.651+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:56:06.659+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:56:17.047+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:56:17.064+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:56:20.932+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:56:20.974+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:56:26.713+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:56:26.716+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:56:29.427+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:56:29.431+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:56:35.027+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:56:35.034+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:56:39.903+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:56:39.906+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:56:48.333+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:56:48.381+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:56:53.312+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:56:53.319+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:56:58.519+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:56:58.520+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:57:02.928+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:57:02.941+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:57:05.733+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:57:05.739+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:57:13.710+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:57:13.715+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:57:21.658+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:57:21.666+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:57:34.020+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:57:34.093+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:57:47.428+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:57:47.435+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:57:53.540+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:57:53.557+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:58:03.904+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:58:03.917+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:58:14.223+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:58:14.240+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:58:24.155+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:58:24.160+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:58:37.604+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:58:37.611+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:58:51.646+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:58:51.715+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:59:10.722+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:59:10.785+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:59:23.743+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:59:23.780+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:59:38.406+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:59:38.414+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T15:59:52.771+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T15:59:52.850+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:00:07.525+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:00:07.542+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:00:19.669+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:00:19.692+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:00:36.717+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:00:36.779+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:00:59.485+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:00:59.521+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:02:09.537+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:02:09.713+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:04:26.707+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:04:26.756+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:05:58.462+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:05:58.540+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:06:50.386+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:06:50.391+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:06:57.772+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:06:57.776+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:07:07.618+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:07:07.632+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:07:15.455+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:07:15.476+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:07:26.826+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:07:26.830+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:07:31.884+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:07:31.895+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:07:42.329+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:07:42.345+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:07:50.356+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:07:50.410+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:08:08.245+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:08:08.259+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:08:20.796+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:08:20.834+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:08:32.197+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:08:32.232+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:08:47.652+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:08:47.668+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:08:58.556+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:08:58.572+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:09:11.734+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:09:11.742+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:09:25.569+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:09:25.582+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:09:48.925+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:09:49.038+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:10:39.652+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:10:39.733+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:11:13.916+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:11:13.943+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:11:33.858+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:11:33.885+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:11:54.245+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:11:54.256+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:12:07.631+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:12:07.649+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:13:04.713+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:13:04.750+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:17:03.036+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:17:03.083+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:19:05.900+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:19:05.914+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:19:14.467+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:19:14.499+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:19:23.972+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:19:23.979+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:19:30.141+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:19:30.146+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:19:35.523+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:19:35.528+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:19:39.784+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:19:39.804+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:19:45.382+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:19:45.390+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:19:53.498+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:19:53.503+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:20:02.552+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:20:02.587+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:20:13.257+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:20:13.367+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:20:24.065+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:20:24.132+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:20:37.986+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:20:38.017+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:20:50.857+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:20:50.893+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:21:10.883+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:21:10.893+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:22:25.660+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:22:25.750+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:23:47.700+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:23:47.753+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:24:09.280+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:24:09.312+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:24:17.785+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:24:17.789+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:24:24.703+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:24:24.733+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:24:33.280+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:24:33.283+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:24:46.397+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:24:46.404+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:24:51.485+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:24:51.489+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:24:54.297+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:24:54.305+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:24:56.586+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:24:56.615+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:00.737+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:00.786+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:05.011+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:05.020+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:11.663+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:11.666+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:17.253+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:17.258+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:20.160+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:20.170+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:23.964+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:23.994+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:28.511+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:28.516+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:34.711+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:34.715+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:37.811+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:37.845+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:39.118+0000] {local_task_job.py:273} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-04-04T16:25:39.351+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 718. PIDs of all processes in the group: [718]
[2025-04-04T16:25:39.363+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 718
[2025-04-04T16:25:39.369+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-04T16:25:39.374+0000] {entry_points.py:53} WARNING - Error when retrieving package metadata (skipping it): <importlib_metadata.PathDistribution object at 0x7fda80bde5d0>, Task received SIGTERM signal
[2025-04-04T16:25:43.604+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:43.610+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:47.037+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:47.044+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:49.409+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:49.418+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:52.706+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:52.724+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:55.434+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:55.440+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:25:59.037+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:25:59.038+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:01.846+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:01.849+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:04.289+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:04.295+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:07.478+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:07.485+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:10.472+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:10.477+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:12.946+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:12.956+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:14.847+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:14.849+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:16.388+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:16.398+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:17.862+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:17.864+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:19.198+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:19.202+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:21.810+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:21.814+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:23.584+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:23.587+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:25.130+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:25.136+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:28.095+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:28.107+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:30.013+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:30.018+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:31.788+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:31.799+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:34.121+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:34.130+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:36.158+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-04-04T16:26:36.160+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='minio_s3', conn_type='aws') credentials retrieved from login and password.
[2025-04-04T16:26:39.398+0000] {process_utils.py:147} WARNING - process psutil.Process(pid=718, name='airflow task ru', status='running', started='15:40:05') did not respond to SIGTERM. Trying SIGKILL
[2025-04-04T16:26:39.587+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGKILL to group 718
[2025-04-04T16:26:39.693+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=718, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='15:40:05') (718) terminated with exit code Negsignal.SIGKILL
[2025-04-04T16:26:39.701+0000] {standard_task_runner.py:170} ERROR - Job 821 was killed before it finished (likely due to running out of memory)
